# Generated by Django 3.1.1 on 2021-02-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
